# Generated by Django 2.2.16 on 2021-11-13 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20211113_1958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['id'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
