# Generated by Django 2.2.16 on 2021-11-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20211113_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(default=1, max_length=200, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
